import Head from "next/head";
import Menu from "../components/Menu";
import NavBar from "../components/navigation/NavBar";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Martins Ngene</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {/* <Menu /> */}
    </div>
  );
};

export default Home;
