/** @format */

import Head from "next/head";
import AboutSection from "../components/about";
import CertificationModule from "../components/certifications";
import HomeSection from "../components/home";
import Layout from "../components/layout";
import PortfolioModule from "../components/portfolio";
import SkillsModule from "../components/skills";
// import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <>
      <Head>
        <title>Martins Ngene</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <HomeSection />
        <AboutSection />
        <PortfolioModule />
        <SkillsModule />
        <CertificationModule />
        {/* <a
          target='_blank'
          href='https://icons8.com/icon/Sx0c8V3R9jEJ/auth0-the-solution-you-need-for-web%2C-mobile%2C-iot%2C-and-internal-applications.'>
          Auth0 the solution you need for web, mobile, IoT, and internal
          applications.
        </a>{" "}
        icon by{" "}
        <a target='_blank' href='https://icons8.com'>
          Icons8
        </a> */}
      </Layout>
    </>
  );
};

export default Home;
