/** @format */

import Head from "next/head";
import AboutSection from "../components/about";
import HomeSection from "../components/home";

import Layout from "../components/layout";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <>
      <Head>
        <title>Martins Ngene</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <HomeSection />
        <AboutSection />
      </Layout>
    </>
  );
};

export default Home;
